### PR TITLE
Kuka office lite

### PR DESCRIPTION
**Pull request by coolafabbe**
Pull request for Kuka officelite

### CODE REVIEW

**Comment by MikelAyani** [comment]
@coolafabbe är det redo för att kika på den?

**Comment by coolafabbe** [comment]
@MikelAyani yes, det ska bara vara att mergea

**Review by MikelAyani — CHANGES_REQUESTED** [review]
My suggestion is to avoid the dependency of openshowvar. It is just a file, the repo has not been updated in two years, and we can integrate the code on that file in a simple way on our own driver. It also has to be more clear in the name and the description of our driver exactly which API/Interface of OficeLite we are using. Does this require installing or enabling something in he Robot?

**Comment by MikelAyani** [comment]
I will suggest that we fix and publish this diver using KukavarProxy for now. In that case we need to have in our documentation a link to KukavarProxy and explain the process of setting all up. In the future we could avoid having a none official middleware like we did with PLCSim and Net2PLCSim... But we will need to find the documentation of Y200 or reverse engineer the KukavarProxy.

**Comment by MikelAyani** [comment]
The project is now OpenSource so maybe is not that difficult to reverse Engineer: 
https://github.com/ImtsSrl/KUKAVARPROXY

**Comment by MikelAyani** [comment]
After some investigation KUKAVARPROXY uses CROSSCOMMEXE and I am not sure what s the difference with Y200.
https://drive.google.com/file/d/1vwXd4ku2j4kuwQUtp_7PllpzyPJ7zyz9/view?usp=share_link

**Review by MikelAyani — APPROVED** [review]

**Pull request merged**
